from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QComboBox,
    QFormLayout,
    QGroupBox,
    QLabel,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)

from behaviour_profile_resolver.firefighter_registry import DEFAULT_FIREFIGHTER_PROFILE_REGISTRY
from behaviour_profile_resolver.occupant_attributes import derive_occupant_attributes
from behaviour_profile_resolver.occupant_grouping import assign_occupant_groups
from behaviour_profile_resolver.registry import DEFAULT_PROFILE_REGISTRY
from behaviour_profile_resolver.resolver import resolve_profile


# =====================================================
# OccupantInspectorPanel -- Simulation Replay Studio V1's "click any
# occupant" requirement. Same convention as every other Command Center
# panel: set_incident() runs once per loaded incident (builds the
# occupant picker and every per-incident derived lookup below),
# show_frame() runs on every playback tick (re-renders whichever
# occupant is currently selected against that frame's own
# IncidentFrame.occupant_positions -- never against a cached value).
#
# Every field below is either read directly off an already-loaded
# artifact (Scenario, IncidentFrame.occupant_positions,
# IncidentData.decision_events) or derived by calling an already-public,
# pure, deterministic function this codebase already uses for exactly
# this purpose at simulation time (behaviour_profile_resolver.
# resolve_profile/occupant_attributes.derive_occupant_attributes/
# occupant_grouping.assign_occupant_groups) -- never a live simulation
# re-run, and never a fabricated value.
#
# Two disclosed, honest simplifications, not oversights:
#
#   1. "Decision Strategy"/"Route Choice Strategy"/"Pre-movement Delay"
#      show the profile TEMPLATE's own base strategy class names
#      (behaviour_profile_resolver.registry.DEFAULT_PROFILE_REGISTRY) --
#      dynamic wrapper strategies (assistance/social-group/crowd-
#      following/attribute-aware -- see behavior_library.
#      attribute_aware_strategies) may further modify what actually
#      happened this run; the label says "(from profile template)"
#      rather than overclaiming precision this artifact set cannot
#      honestly reconstruct.
#   2. "Exit/Stair Guidance" shows the building-wide decision_policy
#      status (KEEP_OPEN/AVOID/...) for whichever exit/stair this
#      occupant actually used -- NOT a personalized "recommendation you
#      received," because no per-occupant routing recommendation is
#      ever generated by the batch scenario-generation pipeline this
#      artifact set is produced by (that mechanism --
#      simulation_interactive.route_manager's own recommended_exit_
#      edge_id/recommended_stair_edge_id traits -- exists only in the
#      separate interactive/live simulation path, never in
#      designer.campaign.campaign_worker/research_framework.runner).
# =====================================================


def _format_value(value, digits=None):

    if value is None:
        return "-"

    if digits is not None and isinstance(value, float):
        return f"{value:.{digits}f}"

    return str(value)


class OccupantInspectorPanel(QWidget):

    def __init__(self, parent=None):
        super().__init__(parent)

        self._incident = None
        self._frame = None
        self._selected_occupant_id = None

        self._occupant_ids = []
        self._is_firefighter_by_id = {}
        self._group_assignment_by_id = {}
        self._assisting_by_id = {}
        self._assisted_by_id = {}
        self._decision_events_by_id = {}

        layout = QVBoxLayout(self)

        self.occupant_combo = QComboBox()
        self.occupant_combo.currentTextChanged.connect(self._on_combo_changed)
        layout.addWidget(self.occupant_combo)

        identity_group = QGroupBox("Identity & Profile")
        identity_form = QFormLayout(identity_group)

        self.zone_value = QLabel("-")
        self.stair_value = QLabel("-")
        self.profile_value = QLabel("-")
        self.decision_strategy_value = QLabel("-")
        self.route_choice_strategy_value = QLabel("-")
        self.pre_movement_value = QLabel("-")

        identity_form.addRow("Current Zone:", self.zone_value)
        identity_form.addRow("Current Stair:", self.stair_value)
        identity_form.addRow("Behavior Profile:", self.profile_value)
        identity_form.addRow("Decision Strategy (from profile template):", self.decision_strategy_value)
        identity_form.addRow("Route Choice Strategy (from profile template):", self.route_choice_strategy_value)
        identity_form.addRow("Pre-movement Delay (from profile template):", self.pre_movement_value)
        layout.addWidget(identity_group)

        movement_group = QGroupBox("Current Movement")
        movement_form = QFormLayout(movement_group)

        self.state_value = QLabel("-")
        self.destination_value = QLabel("-")
        self.speed_value = QLabel("-")

        movement_form.addRow("Current State:", self.state_value)
        movement_form.addRow("Destination:", self.destination_value)
        movement_form.addRow("Speed:", self.speed_value)
        layout.addWidget(movement_group)

        social_group = QGroupBox("Assistance & Group")
        social_form = QFormLayout(social_group)

        self.assisting_value = QLabel("-")
        self.assisted_value = QLabel("-")
        self.leader_follower_value = QLabel("-")
        self.exit_guidance_value = QLabel("-")

        social_form.addRow("Assisting another occupant?", self.assisting_value)
        social_form.addRow("Being assisted?", self.assisted_value)
        social_form.addRow("Leader / Follower:", self.leader_follower_value)
        social_form.addRow("Exit/Stair Guidance (building-wide):", self.exit_guidance_value)
        layout.addWidget(social_group)

        attributes_group = QGroupBox("Derived Physical/Behavioral Attributes")
        attributes_form = QFormLayout(attributes_group)

        self.compliance_value = QLabel("-")
        self.panic_susceptibility_value = QLabel("-")
        self.crowd_following_value = QLabel("-")
        self.risk_aversion_value = QLabel("-")

        attributes_form.addRow("Compliance:", self.compliance_value)
        attributes_form.addRow("Panic Susceptibility:", self.panic_susceptibility_value)
        attributes_form.addRow("Crowd-Following Tendency:", self.crowd_following_value)
        attributes_form.addRow("Risk Aversion:", self.risk_aversion_value)
        layout.addWidget(attributes_group)

        timeline_group = QGroupBox("Decision Timeline")
        timeline_layout = QVBoxLayout(timeline_group)
        self.decision_table = QTableWidget(0, 3)
        self.decision_table.setHorizontalHeaderLabels(["Event", "Related Occupant", "Reason"])
        self.decision_table.horizontalHeader().setStretchLastSection(True)
        self.decision_table.verticalHeader().setVisible(False)
        timeline_layout.addWidget(self.decision_table)
        layout.addWidget(timeline_group)

        layout.addStretch(1)

    # =====================================================
    # Public API -- pushed updates only.
    # =====================================================

    def set_incident(self, incident_data):

        self._incident = incident_data

        self.occupant_combo.blockSignals(True)
        self.occupant_combo.clear()

        self._occupant_ids = []
        self._is_firefighter_by_id = {}
        self._group_assignment_by_id = {}
        self._assisting_by_id = {}
        self._assisted_by_id = {}
        self._decision_events_by_id = {}

        if incident_data is not None:

            scenario = incident_data.scenario

            for occupant in scenario.occupants:
                self._occupant_ids.append(occupant.occupant_id)
                self._is_firefighter_by_id[occupant.occupant_id] = False

                if occupant.assisting_occupant_id:
                    self._assisting_by_id[occupant.occupant_id] = (
                        occupant.assisting_occupant_id, occupant.assistance_type,
                    )
                    self._assisted_by_id[occupant.assisting_occupant_id] = (
                        occupant.occupant_id, occupant.assistance_type,
                    )

            for firefighter in scenario.firefighters:
                self._occupant_ids.append(firefighter.firefighter_id)
                self._is_firefighter_by_id[firefighter.firefighter_id] = True

            self._group_assignment_by_id = assign_occupant_groups(scenario)

            for event in incident_data.decision_events:

                if event.get("event_type") in ("Help_Decision", "Help_Rejected") and event.get("occupant_id"):

                    if event["event_type"] == "Help_Decision":
                        target_id = event.get("related_occupant_id")
                        assistance_type = event.get("metadata", {}).get("assistance_type")
                        self._assisting_by_id.setdefault(
                            event["occupant_id"], (target_id, assistance_type),
                        )
                        if target_id:
                            self._assisted_by_id.setdefault(
                                target_id, (event["occupant_id"], assistance_type),
                            )

                for occupant_id in (event.get("occupant_id"), event.get("related_occupant_id")):
                    if occupant_id:
                        self._decision_events_by_id.setdefault(occupant_id, []).append(event)

            self._occupant_ids = sorted(self._occupant_ids)
            self.occupant_combo.addItems(self._occupant_ids)

        self.occupant_combo.blockSignals(False)

        self._selected_occupant_id = self._occupant_ids[0] if self._occupant_ids else None

        first_frame = incident_data.frame_at_index(0) if incident_data is not None else None
        self.show_frame(first_frame)

    # =====================================================

    def show_frame(self, frame):

        self._frame = frame
        self._render()

    # =====================================================

    def select_occupant(self, occupant_id):

        # The one entry point BuildingView.occupant_clicked (a floor-plan
        # marker click) and this panel's own combo box both drive --
        # keeps both selection paths in perfect sync via Dashboard's own
        # wiring (see command_center/dashboard.py).

        if occupant_id not in self._occupant_ids:
            return

        self._selected_occupant_id = occupant_id

        self.occupant_combo.blockSignals(True)
        self.occupant_combo.setCurrentText(occupant_id)
        self.occupant_combo.blockSignals(False)

        self._render()

    # =====================================================
    # Internal wiring
    # =====================================================

    def _on_combo_changed(self, occupant_id):

        if not occupant_id:
            return

        self._selected_occupant_id = occupant_id
        self._render()

    # =====================================================

    def _render(self):

        self.decision_table.setRowCount(0)

        occupant_id = self._selected_occupant_id

        if self._incident is None or occupant_id is None:

            for label in (
                self.zone_value, self.stair_value, self.profile_value,
                self.decision_strategy_value, self.route_choice_strategy_value, self.pre_movement_value,
                self.state_value, self.destination_value, self.speed_value,
                self.assisting_value, self.assisted_value, self.leader_follower_value,
                self.exit_guidance_value, self.compliance_value, self.panic_susceptibility_value,
                self.crowd_following_value, self.risk_aversion_value,
            ):
                label.setText("-")

            return

        incident = self._incident
        scenario = incident.scenario
        is_firefighter = self._is_firefighter_by_id.get(occupant_id, False)

        profile_id = self._behaviour_profile_id(scenario, occupant_id, is_firefighter)
        self.profile_value.setText(_format_value(profile_id))

        registry = DEFAULT_FIREFIGHTER_PROFILE_REGISTRY if is_firefighter else DEFAULT_PROFILE_REGISTRY
        try:
            template = resolve_profile(profile_id, registry) if profile_id else None
        except Exception:
            template = None

        if template is not None:
            self.decision_strategy_value.setText(type(template.decision_strategy).__name__)
            self.route_choice_strategy_value.setText(type(template.route_choice_strategy).__name__)
            self.pre_movement_value.setText(type(template.pre_movement_strategy).__name__)
        else:
            self.decision_strategy_value.setText("-")
            self.route_choice_strategy_value.setText("-")
            self.pre_movement_value.setText("-")

        if profile_id:
            attributes = derive_occupant_attributes(scenario.metadata.seed, occupant_id, profile_id)
            self.compliance_value.setText(f"{attributes.compliance:.2f}")
            self.panic_susceptibility_value.setText(f"{attributes.panic_susceptibility:.2f}")
            self.crowd_following_value.setText(f"{attributes.crowd_following_tendency:.2f}")
            self.risk_aversion_value.setText(f"{attributes.risk_aversion:.2f}")
        else:
            self.compliance_value.setText("-")
            self.panic_susceptibility_value.setText("-")
            self.crowd_following_value.setText("-")
            self.risk_aversion_value.setText("-")

        position = self._frame.occupant_positions.get(occupant_id) if self._frame is not None else None

        if position is not None:

            self.zone_value.setText(incident.name_for(position.zone_id) if position.zone_id else "-")
            self.stair_value.setText(
                incident.name_for(position.current_stair_id) if position.current_stair_id else "-",
            )
            self.state_value.setText(position.state.replace("_", " ").title())
            self.destination_value.setText(
                incident.name_for(position.current_node_id) if position.current_node_id else "-",
            )
            self.speed_value.setText(
                f"{position.speed:.2f} m/s" if position.speed is not None else "-",
            )

        else:

            self.zone_value.setText("-")
            self.stair_value.setText("-")
            self.state_value.setText("-")
            self.destination_value.setText("-")
            self.speed_value.setText("-")

        assisting = self._assisting_by_id.get(occupant_id)
        self.assisting_value.setText(
            f"Yes -- {incident.name_for(assisting[0])} ({assisting[1] or '-'})" if assisting else "No",
        )

        assisted = self._assisted_by_id.get(occupant_id)
        self.assisted_value.setText(
            f"Yes -- helped by {incident.name_for(assisted[0])} ({assisted[1] or '-'})" if assisted else "No",
        )

        assignment = self._group_assignment_by_id.get(occupant_id)
        if assignment is None:
            self.leader_follower_value.setText("Not in a social group")
        elif assignment.is_leader:
            self.leader_follower_value.setText(f"Leader ({assignment.group_type})")
        else:
            self.leader_follower_value.setText(
                f"Follower of {incident.name_for(assignment.leader_occupant_id)} ({assignment.group_type})",
            )

        self.exit_guidance_value.setText(self._exit_guidance(occupant_id))

        for event in self._decision_events_by_id.get(occupant_id, []):
            self._append_decision_row(event)

    # =====================================================

    def _behaviour_profile_id(self, scenario, occupant_id, is_firefighter):

        if is_firefighter:
            for firefighter in scenario.firefighters:
                if firefighter.firefighter_id == occupant_id:
                    return firefighter.behaviour_profile_id
            return None

        for occupant in scenario.occupants:
            if occupant.occupant_id == occupant_id:
                return occupant.behaviour_profile_id

        return None

    # =====================================================

    def _exit_guidance(self, occupant_id):

        # The last Door/Exit/Stair edge this occupant's own recorded
        # route actually crossed, matched against that same object's
        # own building-wide decision_policy status -- see this module's
        # own docstring for why this is guidance, not a personalized
        # "recommendation you received."

        record = None
        for candidate in self._incident.occupant_routes:
            if candidate.occupant_id == occupant_id:
                record = candidate
                break

        if record is None or not record.hops or self._incident.decision_policy is None:
            return "-"

        last_hop = record.hops[-1]
        policy = self._incident.decision_policy

        for entry in getattr(policy, "exit_decisions", ()):
            if entry.get("exit_id") == last_hop.edge_id:
                return f"Exit -- {entry.get('status', '-')}"

        for entry in getattr(policy, "stair_decisions", ()):
            if entry.get("stair_id") == last_hop.edge_id:
                return f"Stair -- {entry.get('status', '-')}"

        return "-"

    # =====================================================

    def _append_decision_row(self, event):

        row = self.decision_table.rowCount()
        self.decision_table.insertRow(row)

        self.decision_table.setItem(row, 0, QTableWidgetItem(str(event.get("event_type", "-"))))

        related_id = event.get("related_occupant_id")
        related_name = self._incident.name_for(related_id) if related_id else "-"
        self.decision_table.setItem(row, 1, QTableWidgetItem(related_name))

        self.decision_table.setItem(row, 2, QTableWidgetItem(str(event.get("reason", "-"))))
