from dataclasses import dataclass
from typing import Optional, Tuple

from scenario.serialization import position_from_list, position_to_list


@dataclass(frozen=True)
class ScenarioFirefighter:

    # Human Population & Assisted Evacuation Modeling Phase 4/5 --
    # firefighters are NOT ordinary occupants (that phase's own rule),
    # so they are deliberately their own record type here, never a
    # ScenarioOccupant with a firefighter-flavored behaviour_profile_id
    # -- generated by a separate scenario_generator pass (§ Phase 5:
    # "generate firefighter deployments independently from occupant
    # populations"), resolved by a separate
    # behaviour_profile_resolver.firefighter_registrar against a
    # separate registry, using separate behavior_library.
    # firefighter_strategies -- kept apart end to end, per that phase's
    # own "keep firefighter logic separate from civilian behavior
    # logic" rule.
    #
    # behaviour_profile_id is the same opaque-identifier-string
    # convention ScenarioOccupant.behaviour_profile_id already
    # establishes, resolved only against
    # behaviour_profile_resolver.firefighter_registry's own registry,
    # never the civilian one. team_id groups firefighters deployed
    # together (Phase 5's own "configurable team sizes"); arrival_time
    # is when this firefighter enters the building (Phase 5's own
    # "configurable arrival times") -- distinct from a civilian
    # occupant's depart_time, which is a Behavior Layer pre-movement-
    # delay outcome, not a Scenario-authored fact.
    #
    # rescue_target_occupant_id/rescue_target_zone_id are optional and
    # both None by default -- a firefighter deployed with no rescue
    # assignment simply searches/patrols (Phase 4's "searching rooms");
    # both are Scenario-authored (assigned at generation time, §5),
    # never inferred or reassigned during simulation, mirroring
    # ScenarioOccupant.assisting_occupant_id's identical "decided once,
    # upstream of simulation" convention (§3's own note on why:
    # BehaviorProfile.traits/BehaviorDecision.metadata never survive
    # into MultiAgentSimulationResult, so anything Ground Truth or a
    # later analysis needs to read back out must already live on
    # Scenario).

    firefighter_id: str
    team_id: str

    entry_zone_id: str
    floor_id: str
    position: Tuple[float, float]

    arrival_time: float

    behaviour_profile_id: str

    rescue_target_occupant_id: Optional[str] = None
    rescue_target_zone_id: Optional[str] = None

    # =====================================================

    def to_dict(self) -> dict:

        return {
            "firefighter_id": self.firefighter_id,
            "team_id": self.team_id,
            "entry_zone_id": self.entry_zone_id,
            "floor_id": self.floor_id,
            "position": position_to_list(self.position),
            "arrival_time": self.arrival_time,
            "behaviour_profile_id": self.behaviour_profile_id,
            "rescue_target_occupant_id": self.rescue_target_occupant_id,
            "rescue_target_zone_id": self.rescue_target_zone_id,
        }

    # =====================================================

    @classmethod
    def from_dict(cls, data: dict) -> "ScenarioFirefighter":

        return cls(
            firefighter_id=data["firefighter_id"],
            team_id=data["team_id"],
            entry_zone_id=data["entry_zone_id"],
            floor_id=data["floor_id"],
            position=position_from_list(data["position"]),
            arrival_time=data["arrival_time"],
            behaviour_profile_id=data["behaviour_profile_id"],
            rescue_target_occupant_id=data.get("rescue_target_occupant_id"),
            rescue_target_zone_id=data.get("rescue_target_zone_id"),
        )
