from dataclasses import dataclass, field
from typing import Optional, Tuple

from scenario.engineering_state import (
    ScenarioCameraState,
    ScenarioDetectorState,
    ScenarioDoorState,
    ScenarioExitState,
    ScenarioObstacleState,
    ScenarioStairState,
)
from scenario.event import ScenarioEvent
from scenario.fire import ScenarioFire
from scenario.firefighter import ScenarioFirefighter
from scenario.metadata import ScenarioMetadata
from scenario.occupant import ScenarioOccupant
from scenario.serialization import sequence_from_list, sequence_to_list


@dataclass(frozen=True)
class Scenario:

    # The root aggregate a Scenario Generator (§4, a different,
    # not-yet-implemented package) will eventually produce, and a
    # Scenario Validator (§5, likewise not yet implemented) will
    # eventually accept or reject -- architecture doc §7. This class
    # itself performs no computation: it only holds already-resolved
    # values handed to its constructor and knows how to round-trip
    # them through to_dict()/from_dict(). It contains no generation,
    # no validation, no simulation, no navigation, no behaviour logic,
    # no fire physics, no randomness, and no file I/O.
    #
    # Sequence fields are stored as tuples, never lists -- a plain list
    # field inside a frozen dataclass is still mutable in place (frozen
    # only blocks attribute *reassignment*), so __post_init__ below
    # converts whatever iterable the caller passed into a tuple, the
    # same way every dict-shaped field elsewhere in this package is
    # wrapped in a MappingProxyType.
    #
    # difficulty is Optional[float] and absent (None) until a
    # not-yet-implemented post-validation scoring step sets it (§10) --
    # this package never computes it, only carries whatever value it is
    # given.

    metadata: ScenarioMetadata

    occupants: Tuple[ScenarioOccupant, ...] = field(default_factory=tuple)
    fire: Optional[ScenarioFire] = None

    door_states: Tuple[ScenarioDoorState, ...] = field(default_factory=tuple)
    exit_states: Tuple[ScenarioExitState, ...] = field(default_factory=tuple)
    stair_states: Tuple[ScenarioStairState, ...] = field(default_factory=tuple)
    obstacle_states: Tuple[ScenarioObstacleState, ...] = field(default_factory=tuple)
    camera_states: Tuple[ScenarioCameraState, ...] = field(default_factory=tuple)
    detector_states: Tuple[ScenarioDetectorState, ...] = field(default_factory=tuple)

    events: Tuple[ScenarioEvent, ...] = field(default_factory=tuple)

    difficulty: Optional[float] = None

    # Human Population & Assisted Evacuation Modeling Phase 5 --
    # additive. Firefighters are NOT ScenarioOccupants (see
    # scenario.firefighter.ScenarioFirefighter's own docstring for why
    # they are a wholly separate record type) and are generated by a
    # separate scenario_generator pass from occupants -- every existing
    # Scenario construction/serialized payload that predates this field
    # is unaffected, defaulting to an empty tuple (no firefighters
    # deployed).
    firefighters: Tuple[ScenarioFirefighter, ...] = field(default_factory=tuple)

    # =====================================================

    def __post_init__(self):

        object.__setattr__(self, "occupants", tuple(self.occupants))
        object.__setattr__(self, "firefighters", tuple(self.firefighters))
        object.__setattr__(self, "door_states", tuple(self.door_states))
        object.__setattr__(self, "exit_states", tuple(self.exit_states))
        object.__setattr__(self, "stair_states", tuple(self.stair_states))
        object.__setattr__(self, "obstacle_states", tuple(self.obstacle_states))
        object.__setattr__(self, "camera_states", tuple(self.camera_states))
        object.__setattr__(self, "detector_states", tuple(self.detector_states))
        object.__setattr__(self, "events", tuple(self.events))

    # =====================================================

    def to_dict(self) -> dict:

        return {
            "metadata": self.metadata.to_dict(),
            "occupants": sequence_to_list(self.occupants),
            "fire": self.fire.to_dict() if self.fire is not None else None,
            "door_states": sequence_to_list(self.door_states),
            "exit_states": sequence_to_list(self.exit_states),
            "stair_states": sequence_to_list(self.stair_states),
            "obstacle_states": sequence_to_list(self.obstacle_states),
            "camera_states": sequence_to_list(self.camera_states),
            "detector_states": sequence_to_list(self.detector_states),
            "events": sequence_to_list(self.events),
            "difficulty": self.difficulty,
            "firefighters": sequence_to_list(self.firefighters),
        }

    # =====================================================

    @classmethod
    def from_dict(cls, data: dict) -> "Scenario":

        fire_data = data.get("fire")

        return cls(
            metadata=ScenarioMetadata.from_dict(data["metadata"]),
            occupants=sequence_from_list(ScenarioOccupant, data.get("occupants", [])),
            fire=ScenarioFire.from_dict(fire_data) if fire_data is not None else None,
            door_states=sequence_from_list(ScenarioDoorState, data.get("door_states", [])),
            exit_states=sequence_from_list(ScenarioExitState, data.get("exit_states", [])),
            stair_states=sequence_from_list(ScenarioStairState, data.get("stair_states", [])),
            obstacle_states=sequence_from_list(
                ScenarioObstacleState, data.get("obstacle_states", []),
            ),
            camera_states=sequence_from_list(ScenarioCameraState, data.get("camera_states", [])),
            detector_states=sequence_from_list(
                ScenarioDetectorState, data.get("detector_states", []),
            ),
            events=sequence_from_list(ScenarioEvent, data.get("events", [])),
            difficulty=data.get("difficulty"),
            firefighters=sequence_from_list(ScenarioFirefighter, data.get("firefighters", [])),
        )
